version: "3"
services:
  discovery:
    build: ./DiscoveryService/.
    container_name: discovery
    restart: on-failure
    ports:
      - "8761"
    environment:
      - eureka.instance.hostname=discovery
    networks:
      - local-network
  gateway:
    build: ./GatewayService/.
    container_name: gateway
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - discovery
      - auth-service
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
    networks:
      - local-network
  pet-service:
    build: ./PetService/.
    container_name: pet-service
    ports:
      - "8080"
    restart: on-failure
    depends_on:
      - discovery
      - postgresSql
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.url=jdbc:postgresql://db:5432/db_spring_storage
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.username=compose-postgres
      - spring.datasource.password=compose-postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
    networks:
      - local-network
  auth-service:
    build: ./AuthService/.
    container_name: auth-service
    ports:
      - "8080"
    restart: on-failure
    depends_on:
      - discovery
      - user-service
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
    networks:
      - local-network
  user-service:
    build: ./UserService/.
    container_name: user-service
    ports:
      - "8080"
    restart: on-failure
    depends_on:
      - discovery
      - postgresSql
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.url=jdbc:postgresql://db:5432/db_spring_storage
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.username=compose-postgres
      - spring.datasource.password=compose-postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
    networks:
      - local-network
  postgresSql:
    image: 'postgres:14.2-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=db_spring_storage
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432"
    restart: on-failure
    networks:
      - local-network
networks:
  local-network:
