spring:
  application:
    name: user-service

server:
  port: 8080

eureka:
  instance:
    nonSecurePortEnabled: true
    nonSecurePort: ${server.port}
    preferIpAddress: true

logging:
  level:
    ru:
      hartraien: DEBUG

application:
  loginFailedAttemptLimit: 10
  loginFailedAttemptSeconds: 3600
