spring:
  application:
    name: auth-service

server:
  port: 8080

eureka:
  instance:
    nonSecurePortEnabled: true
    nonSecurePort: ${server.port}
    preferIpAddress: true

services:
  names:
    user-service: "lb://user-service"

authorization:
  header-key: "Authorization"

jwt:
  expiration-seconds: 900

logging:
  level:
    ru:
      hartraien: DEBUG

id-claim-name: "id"