spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  instance:
    nonSecurePortEnabled: true
    nonSecurePort: ${server.port}
    preferIpAddress: true

authorization:
  header-key: "Authorization"

services:
  auth-service-url: lb://auth-service
  pet-service-url: lb://pet-service

logging:
  level:
    com:
      example: DEBUG

